### ISSUE TITLE
[Bug]: Improve Existing Backend Logging

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

v2.15.0

### Current Behavior

Today our backend logger uses a lot of `e.toString()` to provide a quick dump of information. It's not great when it happens to be concatenated onto the end of the error string.

### Expected Behavior

Fastify's logger uses two signatures from the underlying library pino.

```
    interface LogFn {
        // TODO: why is this different from `obj: object` or `obj: any`?
        /* tslint:disable:no-unnecessary-generics */
        <T extends object>(obj: T, msg?: string, ...args: any[]): void;
        (obj: unknown, msg?: string, ...args: any[]): void;
        (msg: string, ...args: any[]): void;
    }
```

`(msg: string)` function is wildly used in our app.

We want to move to `(obj: unknown, msg?: string)` for any scenarios where we do a `.toString()` to make use of our logger.

### Steps To Reproduce

Easiest way to do this in dev is to log in as a regular user instead of a cluster admin. Permissions fail and the first error that happens showcases this scenario.

On cluster -- if you can find an error that fits into one of the scenarios listed, that will also be cleaned up a bit.

**Comment by bdattoma** [comment]
@andrewballantyne where these logs appear? in the dashboard pod or in the DevConsole of the browser?

**Comment by manosnoam** [comment]
Logging with non-admin user does not show long toString concatanation:

```
> ods-dashboard-backend@1.0.0 start
> NODE_ENV=production node ./dist/server.js --log=1 --registry=localhost:50051

{"level":30,"time":1697465640701,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Cluster Branding: ocp"}
{"level":30,"time":1697465640734,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Detected no KfDef CRD installed -- suppressing issue pulling KfDef"}
{"level":30,"time":1697465640743,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Pipelines feature enabled, computing operator state..."}
{"level":30,"time":1697465642047,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Server listening at http://0.0.0.0:8080"}
Fastify Connected...
Server listening on >>>  0.0.0.0:8080
{"level":30,"time":1697465642079,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Pipeline Operator status: false"}
{"level":30,"time":1697465642134,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Detected no KfDef CRD installed -- suppressing issue pulling KfDef"}
{"level":30,"time":1697465642135,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Pipelines feature enabled, computing operator state..."}
{"level":50,"time":1697465642138,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Unable to fully convert GPU to use accelerator profiles. A 409 error occurred when trying to create gpu migration configmap: configmaps \"migration-gpu-status\" already exists"}
{"level":30,"time":1697465642143,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"failed to get route jupyterhub in namespace undefined"}
{"level":30,"time":1697465642151,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Pipeline Operator status: false"}
{"level":30,"time":1697465642154,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"failed to get route jupyterhub in namespace undefined"}
{"level":30,"time":1697465688185,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","reqId":"req-1","req":{"method":"GET","url":"/api/health","hostname":"10.129.2.8:8080","remoteAddress":"10.129.2.2","remotePort":58842},"msg":"incoming request"}
{"level":30,"time":1697465688188,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","reqId":"req-1","res":{"statusCode":200},"responseTime":2.589756965637207,"msg":"request completed"}
{"level":30,"time":1697465718181,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","reqId":"req-2","req":{"method":"GET","url":"/api/health","hostname":"10.129.2.8:8080","remoteAddress":"10.129.2.2","remotePort":54000},"msg":"incoming request"}
{"level":30,"time":1697465718182,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","reqId":"req-2","res":{"statusCode":200},"responseTime":0.4389231204986572,"msg":"request completed"}
{"level":30,"time":1697465748181,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","reqId":"req-3","req":{"method":"GET","url":"/api/health","hostname":"10.129.2.8:8080","remoteAddress":"10.129.2.2","remotePort":41698},"msg":"incoming request"}
{"level":30,"time":1697465748182,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","reqId":"req-3","res":{"statusCode":200},"responseTime":0.3442649841308594,"msg":"request completed"}
{"level":30,"time":1697465762147,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Detected no KfDef CRD installed -- suppressing issue pulling KfDef"}
{"level":30,"time":1697465762184,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Pipelines feature enabled, computing operator state..."}
{"level":30,"time":1697465762204,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-cfcpl","msg":"Pipeline Operator status: false"}
```

**Comment by manosnoam** [comment]
Uploading Notebook image with bad url shows:

```
{"level":50,"time":1697540175141,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-h8g5l","err":{"type":"HttpError","message":"HTTP request failed","stack":"HttpError: HTTP request failed\n    at Request._callback (/usr/src/app/backend/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:1482:40)\n    at self.callback (/usr/src/app/backend/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:514:28)\n    at Request.<anonymous> (/usr/src/app/backend/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:514:28)\n    at IncomingMessage.<anonymous> (/usr/src/app/backend/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:628:28)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","response":{"statusCode":400,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"found 'opendatahub.io/notebook-image', expected: ',' or 'end of string'","reason":"BadRequest","code":400},"headers":{"audit-id":"16e9f858-fe67-417c-b5f8-62fa83e4de43, 16e9f858-fe67-417c-b5f8-62fa83e4de43","cache-control":"no-cache, private, no-store","content-length":"186","content-type":"application/json","date":"Tue, 17 Oct 2023 10:56:22 GMT","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-kubernetes-pf-flowschema-uid":"67bc7b8e-04a5-4569-900c-19940e11c87f","x-kubernetes-pf-prioritylevel-uid":"b8d59526-df16-45e5-aa27-18e3fa14a29e","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"172.30.0.1:443","port":"443","hostname":"172.30.0.1","hash":null,"search":"?labelSelector=app.kubernetes.io%2Fcreated-by%3Dbyon%20opendatahub.io%2Fnotebook-image%3Dtrue%20opendatahub.io%2Fdashboard%3Dtrue%20","query":"labelSelector=app.kubernetes.io%2Fcreated-by%3Dbyon%20opendatahub.io%2Fnotebook-image%3Dtrue%20opendatahub.io%2Fdashboard%3Dtrue%20","pathname":"/apis/image.openshift.io/v1/namespaces/redhat-ods-applications/imagestreams","path":"/apis/image.openshift.io/v1/namespaces/redhat-ods-applications/imagestreams?labelSelector=app.kubernetes.io%2Fcreated-by%3Dbyon%20opendatahub.io%2Fnotebook-image%3Dtrue%20opendatahub.io%2Fdashboard%3Dtrue%20","href":"https://172.30.0.1:443/apis/image.openshift.io/v1/namespaces/redhat-ods-applications/imagestreams?labelSelector=app.kubernetes.io%2Fcreated-by%3Dbyon%20opendatahub.io%2Fnotebook-image%3Dtrue%20opendatahub.io%2Fdashboard%3Dtrue%20"},"method":"GET","headers":{"Accept":"application/json","Authorization":"[Redacted]"}}},"body":{"type":"Object","message":"found 'opendatahub.io/notebook-image', expected: ',' or 'end of string'","stack":"","kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","reason":"BadRequest","code":400},"statusCode":400,"name":"HttpError"},"msg":"HTTP request failed"}
{"level":50,"time":1697540175152,"pid":17,"hostname":"rhods-dashboard-74bbdcddd6-h8g5l","err":{"type":"HttpError","message":"HTTP request failed","stack":"HttpError: HTTP request failed\n    at Request._callback (/usr/src/app/backend/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:270:40)\n    at self.callback (/usr/src/app/backend/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:514:28)\n    at Request.<anonymous> (/usr/src/app/backend/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:514:28)\n    at IncomingMessage.<anonymous> (/usr/src/app/backend/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:628:28)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","response":{"statusCode":403,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"imagestreams.image.openshift.io is forbidden: User \"system:serviceaccount:redhat-ods-applications:rhods-dashboard\" cannot create resource \"imagestreams\" in API group \"image.openshift.io\" in the namespace \"redhat-ods-applications\"","reason":"Forbidden","details":{"group":"image.openshift.io","kind":"imagestreams"},"code":403},"headers":{"audit-id":"f120c811-37cf-4839-8465-be21978b6b0c","cache-control":"no-cache, private","content-type":"application/json","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-content-type-options":"nosniff","x-kubernetes-pf-flowschema-uid":"67bc7b8e-04a5-4569-900c-19940e11c87f","x-kubernetes-pf-prioritylevel-uid":"b8d59526-df16-45e5-aa27-18e3fa14a29e","date":"Tue, 17 Oct 2023 10:56:22 GMT","content-length":"414","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"172.30.0.1:443","port":"443","hostname":"172.30.0.1","hash":null,"search":null,"query":null,"pathname":"/apis/image.openshift.io/v1/namespaces/redhat-ods-applications/imagestreams","path":"/apis/image.openshift.io/v1/namespaces/redhat-ods-applications/imagestreams","href":"https://172.30.0.1:443/apis/image.openshift.io/v1/namespaces/redhat-ods-applications/imagestreams"},"method":"POST","headers":{"Accept":"application/json","Authorization":"[Redacted]","content-type":"application/json","content-length":838}}},"body":{"type":"Object","message":"imagestreams.image.openshift.io is forbidden: User \"system:serviceaccount:redhat-ods-applications:rhods-dashboard\" cannot create resource \"imagestreams\" in API group \"image.openshift.io\" in the namespace \"redhat-ods-applications\"","stack":"","kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","reason":"Forbidden","details":{"group":"image.openshift.io","kind":"imagestreams"},"code":403},"statusCode":403,"name":"HttpError"},"msg":"Unable to add notebook image"}
```
