### ISSUE TITLE
[Bug]: HTTPError AlreadyExists after missing ODHDashboardConfig is created by odh-dashboard pod

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying odh-dashboard into a namespace that does not have an existing `ODHDashboardConfig` the logs show an `HTTPError` exception with `Reason: Already Exists`.

### Expected Behavior

Missing ODHDashboardConfig is created and any parallel pods check to see if one already exists before attempting to create a new one.

### Steps To Reproduce

1. Deploy odh-dashboard into a namespace that does not have an existing ODHDashboardConfig
2. Check logs to see if there are any error due creating a default dashboard config when one already exists

### Workaround (if any)

Doesn't appear to affect functionality

### OpenShift Version

OpenStack

### Openshift Version

OCP 4.10

### What browsers are you seeing the problem on?

Chrome

### Open Data Hub Version

```yml
ODH 1.3
```

### Relevant log output

```shell
{"level":40,"time":1657566149315,"pid":108,"hostname":"odh-dashboard-74c44ff58-dm6sp","msg":"Received error fetching OdhDashboardConfig, creating new."}
{"level":50,"time":1657566149353,"pid":108,"hostname":"odh-dashboard-74c44ff58-dm6sp","response":{"statusCode":409,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"odhdashboardconfigs.opendatahub.io \"odh-dashboard-config\" already exists","reason":"AlreadyExists","details":{"name":"odh-dashboard-config","group":"opendatahub.io","kind":"odhdashboardconfigs"},"code":409},"headers":{"audit-id":"a09e12b2-07f4-41f9-88d3-513f63c0183b","cache-control":"no-cache, private","content-type":"application/json","x-kubernetes-pf-flowschema-uid":"4c141507-8e53-4afe-9ffa-1484e4b3ef28","x-kubernetes-pf-prioritylevel-uid":"7441e22c-c4f1-4df3-8a93-cac901fccbe6","date":"Mon, 11 Jul 2022 19:02:28 GMT","content-length":"288","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"172.30.0.1:443","port":"443","hostname":"172.30.0.1","hash":null,"search":null,"query":null,"pathname":"/apis/opendatahub.io/v1alpha/namespaces/opendatahub/odhdashboardconfigs","path":"/apis/opendatahub.io/v1alpha/namespaces/opendatahub/odhdashboardconfigs","href":"https://172.30.0.1:443/apis/opendatahub.io/v1alpha/namespaces/opendatahub/odhdashboardconfigs"},"method":"POST","headers":{"Accept":"application/json","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZpNEUyc0t6OTVHaV9VdWFwcnJjVjZydklNX2pERk9zS0pBNE1jblpTTUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTY4OTEwMjEyMCwiaWF0IjoxNjU3NTY2MTIwLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im9wZW5kYXRhaHViIiwicG9kIjp7Im5hbWUiOiJvZGgtZGFzaGJvYXJkLTc0YzQ0ZmY1OC1kbTZzcCIsInVpZCI6IjcxOGMxM2RmLWNhOTgtNDY5Ny1hZTFkLTk5MGMzZDFlNjQyZiJ9LCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoib2RoLWRhc2hib2FyZCIsInVpZCI6IjViNzQxNjA5LTI0NTgtNDg1ZC1hOTFmLWMzODE4ZGNmMGIxOCJ9LCJ3YXJuYWZ0ZXIiOjE2NTc1Njk3Mjd9LCJuYmYiOjE2NTc1NjYxMjAsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuZGF0YWh1YjpvZGgtZGFzaGJvYXJkIn0.gB75forCFghyUp_CDpybXo8xx8LcBihffW6ocW84GGigcVcYCozJSIWHFmOGjKNcN_8M05xq6-cO-bQ3lUiCqzUMJm3gUSoR7BEn1ouvCTiG7fQhJM69P0eZLWovyB5o9Wu2ctVpG6VRJXyjdDj44YeeNF-mvj9n0x6vanB0fVmJ_J9PQtktfstsAs-noPbeiSN9unwm7nkQNiwYAHktc9aEW7ezbXPri_0dQkUdU3QLz1Q1R-9g_zlpYQQU64Nz8sLRJ4u6MDa8S1cqq6Mff9xewEBybL92G6re8bKaZ7DD2WO8SGsaknhc1US0Saj1Z5Mq2VQfw5GYOSaFLsvYv_aCTbCkJbgogfAyjrf0FsNwH5VqhMdBYM0qotsCztGqZwRcXVMTV8K8tUXB3fL6_Y6tbPbi9_LoakZ6dAdISkedlbmzakf2tJYKHXwxNRLfQ3TiQ29Y4BBeRSvzPPeIh3Y29JPYXblqJjTY4KMvdgv4EEVr_D9ZKNoDxu30cgpxf-0OAyu_3gV33mttZG2U0EPfFeSWAiHlh0lN8EnVHAG5OAcEIX2PnFn6WizD_GcvOzF6g5aT-fr_tpfjGFgEyIPML2IXChzRSPnvnVZy_fj2otvftFeK39Aneenchj2V1R0YDaQ0_0CSZ5avPTpmbzV-ZUeciw2rVXFi_ceW_lc","content-type":"application/json","content-length":337}}},"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"odhdashboardconfigs.opendatahub.io \"odh-dashboard-config\" already exists","reason":"AlreadyExists","details":{"name":"odh-dashboard-config","group":"opendatahub.io","kind":"odhdashboardconfigs"},"code":409},"statusCode":409,"name":"HttpError","stack":"HttpError: HTTP request failed\n    at Request._callback (/opt/app-root/src/backend/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:270:40)\n    at Request.self.callback (/opt/app-root/src/backend/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.<anonymous> (/opt/app-root/src/backend/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:400:28)\n    at IncomingMessage.<anonymous> (/opt/app-root/src/backend/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:519:28)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","type":"Error","msg":"HTTP request failed"}
```

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne +1 on this solution.

**Comment by andrewballantyne** [comment]
I've got mixed feelings about this. I think I'm actually going to close this. If they do not have a config at this point in time -- I think we should create one for them. If the subsequent pods try to all create one because you're missing it -- it's a 1-time issue. 

This should give the deployment a config to start modifying. They should have one already after deployment, but if not we should still create one. Parallel pods starting will cause errors I suppose, but it's harmless.
